 export const RAW_QUIZ_DATA = {
            "Duel des capitaines": [
                { points: 20, question: "Écrivain britannique d'origine indienne, j'ai écrit une œuvre qui a suscité de profonds remous dans le monde m'obligeant à me cacher pour échapper à des menaces de mort, notamment une fatwa émise par l'Ayatollah Khamenei en personne. Quel est le nom de cette œuvre ? Je précise que je m'appelle Salman Rushdie.", answer: "Les versets sataniques" },
                { points: 20, question: "Dans quel pays peut-on visiter Man, Daloa, Gagnoa et Korhogo ?", "answer": "la Côte d'Ivoire" },
                { points: 20, question: "Médecin et criminaliste italien né en 1835 et mort en 1909, il est l'un des fondateurs de la criminologie moderne. Il développa la théorie du criminel-né. Comment s'appelle-t-il ?", answer: "Cesare LOMBROSO" },
                { points: 20, question: "Quel nom masculin invariable, d'origine latine signifie 'aveu' ou 'repentir d'une faute commise' ?", answer: "Mea-culpa" },
                { points: 20, question: "Définissez l'acronyme SONAR ?", answer: "Sound Navigation Ranging" },
                { points: 20, question: "Dans quel pays une femme devient pour la première fois bachelière le 17 Aout 1861 ?", answer: "France" },
                { points: 20, question: "Comment appelle-t-on encore l'étude des sceaux ?", answer: "la sigillographie" },
                { points: 20, question: "En quelle année Karl Wilhelm Roentgen reçut-il le Prix Nobel de Physique pour sa découverte des rayons X ?", answer: "1901" },
                { points: 20, question: "En Iran, le refus du port de quel accessoire vestimentaire par les femmes est puni de 70 coups de fouets et de 60 jours d'emprisonnement ?", answer: "Hijab" },
                { points: 20, question: "Comment appelle-t-on une tour élevée portant au sommet une puissante source lumineuse destinée à guider les navires durant la nuit ?", answer: "Phare" },
                { points: 20, question: "Quel adjectif désigne tout ce qui est relatif à la navigation ou aux sports de l'eau ?", answer: "Nautique" },
                { points: 20, question: "Sur la place de marché de quelle ville a été brulée vive Jeanne d'Arc ?", answer: "Rouen" },
                { points: 20, question: "Qui reçut le 1er Prix Nobel de Littérature ?", answer: "René Sully PRUDHOMME" },
                { points: 20, question: "Quel nom d'un singe d'Asie sert aussi à désigner une personne très laide ?", answer: "Macaque" },
                { points: 20, question: "Quel est l'indicatif téléphonique de la Guinée-Conakry ?", answer: "224" },
                { points: 20, question: "Dans quel sport utilise-t-on une boule de 68,5 cm de circonférence et d'un poids maximal de 7,26 kg ?", answer: "Bowling" },
                { points: 20, question: "Quel était le nom de code de l'opération qui a permis de tuer l'ancien ennemi numéro un des Etats-Unis et chef d'Al Qaida Oussama Ben Laden ?", answer: "Geronimo" },
                { points: 20, question: "Au cours d'un procès, comment appelle-t-on le discours de l'accusation ?", answer: "Le réquisitoire" },
                { points: 20, question: "En géographie comment appelle-t-on dans les pays tropicaux, une dépression de terrain inondée pendant la saison des pluies, ou bras mort d'un fleuve ?", answer: "Marigot" },
                { points: 20, question: "Qui reçut le Ballon d'or France Football en 2008 et en 2013 ?", answer: "Cristiano Ronaldo" }
            ],
            // ** Première série d'Éclairs (remplacée par l'utilisateur lors de la première requête) **
            "Éclairs (Série 1)": [ 
                { points : 10, question : "Mesurant 828m de haut et se trouvant à Dubaï, c'est la plus haute tour du monde. Elle se nomme Burj-Khalifa. Combien d'étages fait-elle exactement ?", answer: "164 étages" },
                { points : 10, question : "En médecine comment appelle-t-on cette maladie due à un manque de vitamine B1 et qui se traduit par un œdème du corps et un engourdissement et une faiblesse des jambes?", answer: "Béri-béri" },
                { points : 10, question : "Quelle couleur est intermédiaire entre le blanc et le noir ?", answer: "Gris" },
                { points : 10, question : "Comment appelle-t-on l'angoisse ou la peur que l'on ressent juste avant de se produire en public ou de mettre un projet à exécution ?", answer: "le trac" },
                { points : 10, question : "Quelle ville du Japon sur l'île de Honshu a donné son nom à son industrie automobile qui est l'une des grandes du marché mondial ?", answer: "Toyota" },
                { points : 10, question : "Etoile massive ayant atteint un stade avancé de son évolution, qui explose et se manifeste temporairement par un éclat beaucoup plus élevé ?", answer: "Supernova" },
                { points : 10, question : "Femme de lettres française, disciple et compagne de J-P SARTRE, ardente féministe, elle est l'auteur de romans et d'essais comme Les Mandarins, Le deuxième sexe. De qui parle-t-on ?", answer: "Simone de Beauvoir" },
                { points : 10, question : "Nichée à près de 3 812 mètres d’altitude, à la frontière entre le Pérou et la Bolivie, quel est le plus haut lac navigable du monde ?", answer: "Le lac Titicaca" },
                { points : 10, question : "Dans la culture islamique traditionnelle, quel nom donne-t-on à l’espace privé, généralement réservé aux épouses, concubines et femmes de la famille, au sein d’un palais ou d’une demeure ?", answer: "Le harem" },
                { points : 10, question : "En philosophie, comment appelle-t-on le processus visant à faire découvrir à l’interlocuteur, par une série de questions, les vérités qu’il possède en lui ?", answer: "La Maïeutique" },
               ],
            "Lettre du match (M)": [
                { points : 10, question : "Comment appelle-t-on en médecine le flux périodique chez la femme de liquide sanglant et que l'on désigne souvent par des règles ?", answer: "les menstrues" },
                { points : 10, question : "Quelle échelle, mise au point au XIXᵉ siècle, permet de classer les minéraux et roches selon leur dureté, du plus tendre au plus résistant ?", answer: "Échelle de Mohs" },
                { points : 10, question : "Dérivé de l'espagnol 'vagabond' comment se nomment les chevaux sauvages d'Amérique du Nord ?", answer: "Mustang" },
                { points : 10, question : "Dans quel pays trouve-ton le Pays Dogon et les falaises de Bandiagara ?", answer: "Mali" },
                { points : 10, question : "Quel métal est à la base de tout alliage nommé amalgame ?", answer: "Le mercure" },
                { points : 10, question : "Quel cycliste belge était surnommé Le Cannibale ?", answer: "Eddie Merckx" },
                { points : 10, question : "Quel adjectif signifie qui a l'apparence du marbre ?", answer: "marmoréen" },
                { points : 10, question : "Quel est le métier des 7 nains qui hébergent Blanche-Neige ?", answer: "mineurs" },
                { points : 10, question : "Quel personnage biblique eut son fils à 187 ans et vécut jusqu'à 969 ans ?", answer: "Mathusalem" },
                { points : 10, question : "Quel oiseau marin de l'hémisphère austral peut être royal ou gorfou ?", answer: "Manchot" },
            ],
            "Spécialités : Histoire": [ // Ordre des questions strict
                { points : 10, question : "Quel président américain a signé la proclamation d’émancipation des esclaves en 1863 ?", answer: "Abraham Lincoln" },
                { points : 10, question : "Qui fut le premier empereur romain, initiateur du Principat et fondateur de l’Empire romain ?", answer: "Auguste" },
                { points : 10, question : "Quelle bataille de 1066 a permis à Guillaume le Conquérant de devenir roi d’Angleterre ?", answer: "La bataille d’Hastings" },
                { points : 10, question : "Quel explorateur portugais a contourné l’Afrique pour atteindre l’Inde en 1498 ?", answer: "Vasco de Gama" },
                { points : 10, question : "Quel mur, symbole de la guerre froide, a séparé Berlin-Ouest et Berlin-Est de 1961 à 1989 ?", answer: "Le mur de Berlin" },
            ],
            "Spécialités : Géographie": [ // Ordre des questions strict
                { points : 10, question : "Quel pays possède le plus grand nombre de fuseaux horaires, en comptant ses territoires d’outre-mer ?", answer: "La France" },
                { points : 10, question : "Quel désert, situé en Asie centrale, est le plus vaste en superficie après le Sahara ?", answer: "Le désert de Gobi" },
                { points : 10, question : "Quel lac africain est le plus profond et se situe dans la vallée du Rift ?", answer: "Le lac Tanganyika" },
                { points : 10, question : "Quel pays africain possède la plus longue façade maritime sur l’océan Atlantique ?", answer: "L’Angola" },
                { points : 10, question : "Quel est le plus grand pays enclavé du monde ?", answer: "Le Kazakhstan" },
            ],
            // ** NOUVELLES RUBRIQUES CI-DESSOUS **
            "Spécialités : Art et littérature": [
                { points: 10, question: "Quel peintre espagnol est célèbre pour son tableau « Guernica », dénonçant les horreurs de la guerre ?", answer: "Pablo Picasso" },
                { points: 10, question: "Quel poète français du XIXe siècle a écrit « Les Fleurs du Mal » ?", answer: "Charles Baudelaire" },
                { points: 10, question: "Quel sculpteur italien est l’auteur de la statue de « David » et du plafond de la Chapelle Sixtine ?", answer: "Michel-Ange" },
                { points: 10, question: "Quel écrivain russe a écrit « Guerre et Paix », un roman épique sur l’invasion de la Russie par Napoléon ?", answer: "Léon Tolstoï" },
                { points: 10, question: "Quel mouvement artistique du début du XXe siècle est associé à Salvador Dalí et René Magritte ?", answer: "Le surréalisme" }
            ],
            "Spécialités : Sport": [
                { points: 10, question: "Quel footballeur a inscrit 2 buts de la tête en finale de la Coupe du monde 1998 ?", answer: "Zinédine Zidane" },
                { points: 10, question: "Sous quel nom est plus connu le footballeur brésilien : Edson Arantes Do Nascimento ?", answer: "Pelé" },
                { points: 10, question: "En sport, quel anglicisme désigne la photographie de l'arrivée d'une course ?", answer: "La photo-finish" },
                { points: 10, question: "En octobre 2008, quel ancien footballeur est devenu sélectionneur de l'équipe nationale d'Argentine ?", answer: "Diego Armando Maradona" },
                { points: 10, question: "De quel club de foot argentin le pape François est-il un fervent supporter ?", answer: "Le club de San Lorenzo de Almagro" }
            ],
            "Lettre du match : lettre E": [
                { points: 10, question: "Quel terme désigne la force ou la capacité qui permet d’accomplir un travail ou de produire un mouvement, qu’il soit physique, électrique ou mental ?", answer: "Énergie" },
                { points: 10, question: "Quel outil simple permet de relier deux niveaux en hauteur, grâce à des barreaux qu’on gravit un à un ?", answer: "Échelle" },
                { points: 10, question: "Quel astre, dont notre Soleil est un exemple, brille de sa propre lumière et peuple l’univers par milliards ?", answer: "Étoile" },
                { points: 10, question: "Quel phénomène sonore se produit lorsqu’un bruit est renvoyé par une surface lointaine, donnant l’impression d’une répétition ?", answer: "Écho" },
                { points: 10, question: "Quel mot désigne une manifestation violente, spontanée et désorganisée d’un groupe de personnes en colère contre une autorité ou une injustice ?", answer: "Émeute" },
                { points: 10, question: "Quel sommet, situé dans l’Himalaya à la frontière entre le Népal et la Chine, culmine à 8 848 mètres d’altitude et est considéré comme le plus haut point de la planète Terre ?", answer: "Everest" },
                { points: 10, question: "Quel terme désigne un ensemble d’activités intellectuelles et manuelles visant à former ou à instruire un individu, depuis l’enfance jusqu’à l’âge adulte ?", answer: "Éducation" },
                { points: 10, question: "Quelle est la cinquième lettre de l’alphabet français ?", answer: "E" },
                { points: 10, question: "Quel pays de la Corne de l’Afrique, à l’histoire millénaire, fut l’un des rares États africains à ne jamais avoir été colonisé, et possède une culture chrétienne orthodoxe profondément enracinée ?", answer: "Éthiopie" },
                { points: 10, question: "Quel objet souple et absorbant, d’origine naturelle ou synthétique, est couramment utilisé pour nettoyer ou absorber des liquides ?", answer: "Éponge" }
            ],
            "Thème : Les célèbres auteurs africains": [
                { points: 10, question: "Quel écrivain nigérian, auteur de Le Monde s’effondre, est considéré comme un oublié du prix Nobel ?", answer: "Chinua Achebe" },
                { points: 10, question: "Quelle écrivaine sénégalaise, pionnière du féminisme africain francophone, a bouleversé la scène littéraire en 1979 avec son roman épistolaire Une si longue lettre, dans lequel elle dénonce la polygamie et les injustices faites aux femmes ?", answer: "Mariama Bâ" },
                { points: 10, question: "Quel écrivain ivoirien, célèbre pour avoir donné une voix singulière à l’Afrique postcoloniale en mêlant le français aux rythmes et aux proverbes malinkés, est l’auteur du roman engagé Les Soleils des Indépendances, paru en 1968 ?", answer: "Ahmadou Kourouma" },
                { points: 10, question: "Quel poète et homme d’État sénégalais, cofondateur de la négritude, a été le premier Africain membre de l’Académie française ?", answer: "Léopold Sédar Senghor" },
                { points: 10, question: "Quel dramaturge, poète et militant nigérian est devenu en 1986 le premier écrivain africain à recevoir le prix Nobel de littérature ?", answer: "Wole Soyinka" },
                { points: 10, question: "Quel écrivain camerounais, également diplomate et homme politique, est l’auteur du roman satirique Une vie de boy (1956), dans lequel il dénonce les abus du colonialisme à travers le regard naïf mais lucide d’un jeune domestique africain ?", answer: "Ferdinand Oyono" },
                { points: 10, question: "Quel écrivain guinéen a marqué les débuts de la littérature africaine francophone en 1953 avec L’Enfant noir, un roman autobiographique qui retrace son enfance ?", answer: "Camara Laye" },
                { points: 10, question: "Quel écrivain malien, maître du conte et de la tradition orale, est l’auteur de L’Étrange destin de Wangrin ?", answer: "Amadou Hampâté Bâ" },
                { points: 10, question: "Quel poète, conteur et vétérinaire sénégalais, héritier de la tradition orale africaine, a contribué à la redécouverte de la sagesse des griots dans ses Contes d’Amadou Koumba ?", answer: "Birago Diop" },
                { points: 10, question: "Quel écrivain sénégalais, à travers son roman philosophique L’Aventure ambiguë, interroge le conflit entre tradition africaine et éducation occidentale à travers le parcours de Samba Diallo, tiraillé entre foi, identité et raison ?", answer: "Cheikh Hamidou Kane" }
            ],
            "Éclairs (Série 2)": [ 
                // ** Deuxième série d'Éclairs (ajoutée par l'utilisateur) **
                { points : 10, question : "Ce paquebot de luxe, présenté à l’époque comme « insubmersible », sombra tragiquement après avoir heurté un iceberg dans l’Atlantique Nord, provoquant la mort de 1 513 passagers et laissant 705 survivants. Il s’agit bien sûr du Titanic. Dites-moi, en quelle année cette tragédie a-t-elle eu lieu ?", answer: "1912" },
                { points : 10, question : "Si on additionne ceux accompagnant Blanche Neige à ceux officiant à l'origine dans Fort-Boyard, combien obtient-on de nains ?", answer: "neuf" },
                { points : 10, question : "Quelle cité fut opposée à Athènes lors de la guerre du Péloponnèse ?", answer: "Spartes" },
                { points : 10, question : "De quel empire Manco Capac est-il le fondateur légendaire ?", answer: "Inca" },
                { points : 10, question : "Quel maréchal français fut surnommé 'le vainqueur de Verdun' ?", answer: "Philippe Pétain" },
                { points : 10, question : "Quels personnages de BD sont apparus sous les noms X33 et X33 bis en 1934 ?", answer: "Dupond et Dupont" },
                { points : 10, question : "Quelle version de Windows a succédé à Windows 7 fin 2012 ?", answer: "Windows 8" },
                { points : 10, question : "Que s'abstient de consommer une personne abstème ?", answer: "alcool" },
                { points : 10, question : "Qui résuma sa campagne victorieuse contre Pharnasse 2 par le célèbre 'Veni, Vidi, Vici' ?", answer: "Jules César" },
                { points : 10, question : "Sous quel pseudonyme est plus connu le héros de BD Steve Rodgers, interprété en 2011 par Chris Evans ?", answer: "Captain America" },
            ],
            "Qui, Que, Où suis-je ?": [
                { points: 10, question: "Qui suis-je ? Philosophe grec, élève de Socrate et maître d’Aristote, auteur de « La République ».", answer: "Platon" },
                { points: 10, question: "Que suis-je ? Utilisé en architecture et en sculpture, je suis un support vertical qui soutient un arc ou un plafond, souvent décoré de motifs.", answer: "Un pilier" },
                { points: 10, question: "Où suis-je ? Montagne sacrée où Moïse reçut les tables de la Loi selon la Bible.", answer: "Le Mont Sinaï" },
                { points: 10, question: "Qui suis-je ? Philosophe allemand du XIXe siècle, auteur du « Ainsi parlait Zarathoustra » et théoricien du concept de « volonté de puissance ».", answer: "Friedrich Nietzsche" },
                { points: 10, question: "Que suis-je ? Science qui étudie les nombres, les formes, les espaces et les structures logiques pour résoudre des problèmes abstraits.", answer: "Les mathématiques" },
                { points: 10, question: "Où suis-je ? Ville italienne surnommée « la Sérénissime », célèbre pour ses canaux et son carnaval.", answer: "Venise" },
                { points: 10, question: "Qui suis-je ? Leader sud-africain, symbole de la lutte contre l’apartheid et premier président noir d’Afrique du Sud.", answer: "Nelson Mandela" },
                { points: 10, question: "Que suis-je ? Mot masculin, je désigne aussi bien un avis de contravention qu'un nœud de cravate plat. Je suis surtout un insecte à quatre ailes, après métamorphose de la chenille.", answer: "Un papillon" },
                { points: 10, question: "Où suis-je ? Fleuve africain, deuxième plus long du continent après le Nil, traversant la République Démocratique du Congo.", answer: "Le fleuve Congo" },
                { points: 10, question: "Que suis-je ? Mouvement littéraire et artistique du XVIIe siècle en France, caractérisé par le goût de l’exagération et des effets surprenants.", answer: "Le baroque" }
            ],
            "Thème unique : Les langues du monde": [
                { points: 10, question: "Quelle langue tonale, écrite avec des sinogrammes, est la plus parlée au monde en tant que langue maternelle ?", answer: "Le mandarin" },
                { points: 10, question: "Quelle langue romane, issue du latin vulgaire, est la seule à être parlée sur les cinq continents comme langue officielle ?", answer: "Le français" },
                { points: 10, question: "Quelle langue germanique, devenue lingua franca mondiale, est la plus apprise comme langue étrangère ?", answer: "L’anglais" },
                { points: 10, question: "Quelle langue sémitique, écrite de droite à gauche, est langue officielle dans plus de 20 pays ?", answer: "L’arabe" },
                { points: 10, question: "Quelle langue bantoue, parlée en Afrique de l’Est, est utilisée comme langue véhiculaire au Kenya, en Tanzanie et en Ouganda ?", answer: "Le swahili" },
                { points: 10, question: "Quelle langue indo-européenne, parlée en Amérique latine et en Espagne, est la deuxième langue maternelle la plus parlée au monde ?", answer: "L’espagnol" },
                { points: 10, question: "Quelle langue asiatique, utilisant l’alphabet hangul, est parlée au nord et au sud de la péninsule coréenne ?", answer: "Le coréen" },
                { points: 10, question: "Quelle langue slave, écrite en alphabet cyrillique, est la langue officielle de la Russie ?", answer: "Le russe" },
                { points: 10, question: "Quelle langue germanique, dérivée du néerlandais, est parlée en Afrique du Sud et en Namibie ?", answer: "L’afrikaans" },
                { points: 10, question: "Quelle langue officielle du Luxembourg est un mélange de français, d’allemand et de dialectes mosellans ?", answer: "Le luxembourgeois" }
            ],
            "Lettre du match : Lettre A": [
                { points: 10, question: "Quel est cette organisation secrète dont les membres portaient une robe noire avec des motifs en forme de nuages rouges ?", answer: "Akatsuki" },
                { points: 10, question: "Quel explorateur italien a donné son nom au continent américain après ses voyages et descriptions du Nouveau Monde ?", answer: "Amerigo Vespucci" },
                { points: 10, question: "Quel continent découvert par les Européens à partir du XVe siècle est surnommé le Nouveau Monde ?", answer: "Amérique" },
                { points: 10, question: "Quel émir arabe d'Algérie dirigea pendant quinze ans la résistance algérienne contre la colonisation française ?", answer: "Abd el-Kader" },
                { points: 10, question: "Comment s’appelle celui qui a une peur excessive du public ou des foules ?", answer: "Agoraphobe" },
                { points: 10, question: "Quel fruit tropical, apprécié pour sa chair sucrée et orangée, est aussi surnommé prune malgache ?", answer: "Abricot" },
                { points: 10, question: "Quel pays d’Asie centrale, connu pour son histoire riche et ses paysages montagneux, a pour capitale Kaboul ?", answer: "Afghanistan" },
                { points: 10, question: "Quel est le gaz noble utilisé dans l'éclairage et identifié par le symbole chimique Ar ?", answer: "Argon" },
                { points: 10, question: "Quel métal précieux, connu pour sa brillance et ses usages en joaillerie, porte le symbole chimique Ag ?", answer: "Argent" },
                { points: 10, question: "Quelle ville perchée à plus de 2 000 mètres d’altitude est la capitale de l’Érythrée et un exemple remarquable d’urbanisme moderniste ?", answer: "Asmara" }
            ],
            "Éclairs (Série 3)": [
                { points: 10, question: "Quel roi de France, surnommé Le Roi Soleil, a dirigé le pays pendant plus de 72 ans ?", answer: "Louis XIV" },
                { points: 10, question: "Quelle entreprise spécialisée en intelligence artificielle est à l’origine du développement de ChatGPT ?", answer: "OpenAI" },
                { points: 10, question: "Quelle échelle météorologique, utilisée pour mesurer la force du vent, porte le nom de son créateur et s’étend de 0 à 12 ?", answer: "L’échelle de Beaufort" },
                { points: 10, question: "Comment appelle-t-on une personne qui possède une grande habileté avec ses deux mains, capable d’écrire ou de manipuler des objets avec indifféremment la droite ou la gauche ?", answer: "Un ambidextre" },
                { points: 10, question: "Quel militant américain, célèbre pour sa lutte pour les droits civiques et son éloquence, était connu sous le nom d’El-Hajj Malek El-Shabazz ?", answer: "Malcolm X" },
                { points: 10, question: "Que signifie le mot hébreu Eden ?", answer: "Délice" },
                { points: 10, question: "Comment se nomme la zone d’un volcan où montent les laves et les projections volcaniques ?", answer: "La cheminée" },
                { points: 10, question: "Quel mot commençant par la lettre 'K', est le nom que l'on donne à une fête en plein air, avec des jeux ?", answer: "Kermesse" },
                { points: 10, question: "211 chambres dont 82 ont une vue sur mer, 2 restaurants dont un gastronomique, 2 bars et une piscine olympique, 2 courts de tennis, 1 terrain de golf et un centre d'équitation, quelle hôtel 4 étoiles situé sur la plage de Lomé au milieu d'une cocoteraie de 25 hectares dispose de toutes ces commodités ?", answer: "L'hôtel Sarakawa" },
                { points: 10, question: "Quel volcan éteint est la plus haute montagne du Japon ?", answer: "Fuji-Yama" }
            ],
            "Cascades (A-Z)": [
                { points: 10, question: "Quel manga créé en 1982 nous présente une vision post-apocalyptique de la ville de Néo-Tokyo à travers la plume de Katshuhiro Otomo ?", answer: "Akira", requiredLetter: 'A' },
                { points: 10, question: "Comment appelle-t-on un habitant du Royaume-Uni ?", answer: "Britannique", requiredLetter: 'B' },
                { points: 10, question: "En biologie, de quel élément du noyau des cellules le télomère et le centromère sont-ils des composants ?", answer: "CHROMOSOME", requiredLetter: 'C' },
                { points: 10, question: "D'après une expression proverbiale, combien un homme averti en vaut-il ?", answer: "Deux", requiredLetter: 'D' },
                { points: 10, question: "En 306 avant J.-C., quel philosophe crée à Athènes une école philosophique appelée 'Le Jardin' ?", answer: "Épicure", requiredLetter: 'E' },
                { points: 10, question: "Quel est le prénom du dirigeant politique qui détient le record du plus long discours jamais prononcé à l’Assemblée générale des Nations Unies, avec plus de 4 heures de prise de parole en 1960 ?", answer: "Fidel", requiredLetter: 'F' },
                { points: 10, question: "Le bombardement de quelle petite ville basque a voulu dénoncer Pablo Picasso dans une de ses œuvres ?", answer: "Guernica", requiredLetter: 'G' },
                { points: 10, question: "De quel crime Galilée fut-il accusé pour avoir affirmé que la terre n’était pas au centre de l’univers ?", answer: "Hérésie", requiredLetter: 'H' },
                { points: 10, question: "En art, quel adjectif commençant par la voyelle i désigne une statue dont le sujet est en érection ?", answer: "Ithyphallique", requiredLetter: 'I' },
                { points: 10, question: "Quel hors-la-loi américain était surnommé le 'Brigand bien-aimé' ?", answer: "Jesse James", requiredLetter: 'J' },
                { points: 10, question: "Quel arbre d'Afrique tropicale de la famille des sapotacées fournit une matière grasse d'usage culinaire et cosmétique ?", answer: "Karité", requiredLetter: 'K' },
                { points: 10, question: "En 2011, dans quel pays africain la France intervient-elle à travers l’opération Harmattan ?", answer: "La Libye", requiredLetter: 'L' },
                { points: 10, question: "Quel impressionniste barbu, parfois confondu avec Manet, reste indissociable de ses nymphéas ?", answer: "Claude Monet", requiredLetter: 'M' },
                { points: 10, question: "Qui était président des Etats-Unis d'Amérique lorsque Neil Armstrong a marché sur la Lune ?", answer: "Richard Nixon", requiredLetter: 'N' },
                { points: 10, question: "Quel singe tient son nom du malais signifiant « homme des bois » ?", answer: "L’orang-outan", requiredLetter: 'O' },
                { points: 10, question: "De quelle langue européenne sont issus les mots serval, bambou, macaque et banane ?", answer: "PORTUGAIS", requiredLetter: 'P' },
                { points: 10, question: "Combien y a-t-il d'atomes de fluor dans une molécule de Tétrafluorure de carbone ?", answer: "Quatre", requiredLetter: 'Q' },
                { points: 10, question: "Quelle maladie de l'enfance est principalement due à une carence en vitamine D ?", answer: "Rachitisme", requiredLetter: 'R' },
                { points: 10, question: "Quel pays africain a perdu le quart de sa superficie suite à l’indépendance du Soudan du Sud ?", answer: "Le Soudan", requiredLetter: 'S' },
                { points: 10, question: "Quel nom donne-t-on à la triple couronne, d’origine babylonienne, qui figure sur les armoiries des papes catholiques ?", answer: "Tiare", requiredLetter: 'T' },
                { points: 10, question: "La chanson L’internationale fut l’hymne de quel pays de 1922 à 1944 ?", answer: "L’URSS", requiredLetter: 'U' },
                { points: 10, question: "Le personnage de comics Norman Osborn, un des ennemis emblématiques de Spiderman, est surnommé le Bouffon...", answer: "Vert", requiredLetter: 'V' },
                { points: 10, question: "Quel tournoi, organisé pour la première fois en 1877, est le plus ancien et prestigieux événement du tennis ?", answer: "Wimbledon", requiredLetter: 'W' },
                { points: 10, question: "Par quelle lettre se termine le mot tuyau quand il est écrit au pluriel ?", answer: "X", requiredLetter: 'X' },
                { points: 10, question: "Quelle est la monnaie officielle du Japon ?", answer: "Yen", requiredLetter: 'Y' },
                { points: 10, question: "Quel footballeur a inscrit 2 buts de la tête en finale de la Coupe du monde 1998 ?", answer: "Zinédine Zidane", requiredLetter: 'Z' }
            ],
            // ** NOTE : La rubrique Éclairs (Série 4) de l'historique précédent manque ici, l'utilisateur a demandé d'ajouter Cascades avant l'éclair de fin (qui est Série 3 dans ce contexte) **
            "Éclairs (Série 4)": [ 
                // Données de l'interaction précédente (que j'ai renommée Série 4)
                { points: 10, question: "Quel roi de France, surnommé Le Roi Soleil, a dirigé le pays pendant plus de 72 ans ?", answer: "Louis XIV" },
                { points: 10, question: "Quelle entreprise spécialisée en intelligence artificielle est à l’origine du développement de ChatGPT ?", answer: "OpenAI" },
                { points: 10, question: "Quelle échelle météorologique, utilisée pour mesurer la force du vent, porte le nom de son créateur et s’étend de 0 à 12 ?", answer: "L’échelle de Beaufort" },
                { points: 10, question: "Comment appelle-t-on une personne qui possède une grande habileté avec ses deux mains, capable d’écrire ou de manipuler des objets avec indifféremment la droite ou la gauche ?", answer: "Un ambidextre" },
                { points: 10, question: "Quel militant américain, célèbre pour sa lutte pour les droits civiques et son éloquence, était connu sous le nom d’El-Hajj Malek El-Shabazz ?", answer: "Malcolm X" },
                { points: 10, question: "Que signifie le mot hébreu Eden ?", answer: "Délice" },
                { points: 10, question: "Comment se nomme la zone d’un volcan où montent les laves et les projections volcaniques ?", answer: "La cheminée" },
                { points: 10, question: "Quel mot commençant par la lettre 'K', est le nom que l'on donne à une fête en plein air, avec des jeux ?", answer: "Kermesse" },
                { points: 10, question: "211 chambres dont 82 ont une vue sur mer, 2 restaurants dont un gastronomique, 2 bars et une piscine olympique, 2 courts de tennis, 1 terrain de golf et un centre d'équitation, quelle hôtel 4 étoiles situé sur la plage de Lomé au milieu d'une cocoteraie de 25 hectares dispose de toutes ces commodités ?", answer: "L'hôtel Sarakawa" },
                { points: 10, question: "Quel volcan éteint est la plus haute montagne du Japon ?", answer: "Fuji-Yama" }
            ]
        };

        const SHUFFLEABLE_SECTIONS = [
            "Duel des capitaines",
            "Éclairs (Série 1)",
            "Lettre du match (M)",
            "Spécialités : Histoire",
            "Spécialités : Géographie",
            "Spécialités : Art et littérature",
            "Spécialités : Sport",
            "Lettre du match : lettre E",
            "Thème : Les célèbres auteurs africains",
            "Éclairs (Série 2)",
            "Qui, Que, Où suis-je ?",
            "Thème unique : Les langues du monde",
            "Lettre du match : Lettre A",
            "Éclairs (Série 3)",
            "Cascades (A-Z)",
            "Éclairs (Série 4)",
        ];

        let QUIZ_DATA_FINAL = [];
